apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.backend.env.db.host | quote }}
  DB_PORT: {{ .Values.backend.env.db.port | quote }}
  DB_NAME: {{ .Values.backend.env.db.name | quote }}
  DB_USER: {{ .Values.backend.env.db.user | quote }}
  DB_PASSWORD: {{ .Values.backend.env.db.password | quote }}
  ALLOWED_ORIGINS: {{ .Values.backend.env.allowedOrigins | quote }}
