apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-backend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "todo-app.name" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
