apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ .Values.frontend.env.apiUrl | quote }}
