{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ include "todo-app.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
