spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:todoapp}
    username: ${DB_USER:todo}
    password: ${DB_PASSWORD:todo}

todo:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:8081,http://frontend:80}
