version: "3.9"

networks:
  migration-lab:
    name: migration-lab
    driver: bridge

services:
  target-vm:
    build:
      context: ./target-vm
    container_name: target-vm
    privileged: true
    restart: unless-stopped
    networks:
      - migration-lab
    ports:
      - "80:80"
      - "2222:22"
